name: Ansible Lint
run-name: Ansible Lint - ${{ github.event.head_commit.message }}
on: [push]

jobs:
  ansible-lint-job:
    name: Job to run ansible-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Run ansible-lint
        id: run-lint
        uses: SatyamKumar3/action-ansible-lint@master
        with:
          # repo-name: "${{ github.event.repository.name }}"
          repo-name: "${{ github.workspace }}"