name: Ansible Lint
run-name: Ansible Lint - ${{ github.event.head_commit.message }}
on: [push]

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run ansible-lint
        id: run-lint
        uses: SatyamKumar3/action-ansible-lint@main
      